In [1]:
import numpy as np

In [2]:
 a =np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[2]

3

In [5]:
a[0]

1

Why numpy
1) Fast
2) Convinient
3) Less Memory

In [6]:
import time
import sys

In [7]:
b=range(1000)

In [8]:
print(sys.getsizeof(5)*len(b))

28000


In [9]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [10]:
size =100000

In [11]:
L1=range(size)
l2=range(size)
A1=np.arange(size)
A2=np.arange(size)


In [12]:
a= np.array([[1,2],[2,3],[4,5]])

In [13]:
a

array([[1, 2],
       [2, 3],
       [4, 5]])

In [14]:
a.ndim


2

In [15]:
a.itemsize

4

In [16]:
a.shape

(3, 2)

In [17]:
a= np.array([[1,2],[2,3],[4,5]], dtype=np.float64)

In [18]:
a

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [19]:
a.itemsize

8

In [20]:
a.shape

(3, 2)

In [21]:
a= np.array([[1,2],[2,3],[4,5]], dtype=np.complex)
a

<ipython-input-21-bd8b680f12c9>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a= np.array([[1,2],[2,3],[4,5]], dtype=np.complex)


array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
l=range(5)
l

range(0, 5)

In [25]:
l=np.arange(5)
l

array([0, 1, 2, 3, 4])

In [26]:
print(np.char.title('how are you doing?'))

How Are You Doing?
